### ISSUE TITLE
What is the purpose of the system column?

### ISSUE THREAD

**Issue by jocubeit** [metaminded/meta_types#2]
In `/db/migrate/ 20120507130255_meta_type_property.rb`:

``` ruby
system            boolean not null default false,
```

Also what is the `dimension` column used for? Is it used to describe the MetaTypeProperty value? e.g. Megabytes, Pounds...

**Comment by no-dashes** [comment]
The <tt>system</tt> column is meant as an "don't change me for I am used in the code". I added an <tt>editable</tt> scope to <tt>MetaTypeProperty</t> to be able to only retrieve the non-system MetaTypeProperties for editing.
I just want to prevent that someone changes the firstname-column to date :)

W.r.t. the <tt>dimension</tt> column: You're absolutely right.

**Comment by jocubeit** [comment]
Awesome, thanks Peter.
