### ISSUE TITLE
Table structure in models

### ISSUE THREAD

**Issue by jocubeit** [metaminded/meta_types#4]
In `app/models` are the `<<-CREATE_SQL` blocks there to document the table structure?

If so, they should probably be commented out as they serve no useful purpose for the model.

``` ruby
# id          serial PRIMARY KEY,
# sid         character varying not null UNIQUE,
# title       character varying not null UNIQUE,
# created_at  timestamp without time zone,
# updated_at  timestamp without time zone
```

**Comment by no-dashes** [comment]
Point taken... The advantage is that copy-pasting was easier this way :)
